### GET index
GET localhost:3000

### GET categories
GET localhost:3000/categories

### POST categories
POST localhost:3000/categories
Content-Type: application/json

{
  "name": "testing 3",
  "description": "nyoba testing lagi 3"
}

### POST user registration
POST localhost:3000/users/register
Content-Type: application/json

{
  "username": "user_1",
  "password": "root123"
}

### POST user authorization password grant type
POST localhost:3000/oauth/authorize
Content-Type: application/json

{
  "username": "user_1",
  "password": "root123",
  "scope": "read",
  "grantType": "password",
  "clientId": "test_client_1"
}

### POST user authorization refresh_token grant type
POST localhost:3000/oauth/authorize
Content-Type: application/json

{
  "scope": "read",
  "grantType": "refresh_token",
  "refreshToken": "479440cf-37b0-4e84-bdf6-dc42f059057c",
  "clientId": "test_client_1"
}