### GET index
GET localhost:3000

### GET categories
GET localhost:3000/categories

### POST categories
POST localhost:3000/categories
Content-Type: application/json

{
  "name": "testing 3",
  "description": "nyoba testing lagi 3"
}

### POST user registration
POST localhost:3000/users/register
Content-Type: application/json

{
  "username": "user_1",
  "password": "root123"
}

### POST user authorization
POST localhost:3000/oauth/authorize
Content-Type: application/json

{
  "username": "user_1",
  "password": "root123",
  "scope": "read",
  "grantType": "passwords",
  "clientId": "test_client_1"
}