// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"forum-app/config"
	"forum-app/controller"
	"forum-app/service"
	"github.com/google/wire"
)

// Injectors from injector.go:

func InitializeCategoryController() *controller.CategoryControllerImpl {
	db := config.NewDbSession()
	categoryServiceImpl := service.NewCategoryService(db)
	categoryControllerImpl := controller.NewCategoryController(categoryServiceImpl)
	return categoryControllerImpl
}

// injector.go:

var categorySet = wire.NewSet(service.NewCategoryService, wire.Bind(new(service.CategoryService), new(*service.CategoryServiceImpl)), controller.NewCategoryController, wire.Bind(new(controller.CategoryController), new(*controller.CategoryControllerImpl)))
