// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// CategoryTable is an autogenerated mock type for the CategoryTable type
type CategoryTable struct {
	mock.Mock
}

// TableName provides a mock function with given fields:
func (_m *CategoryTable) TableName() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

type mockConstructorTestingTNewCategoryTable interface {
	mock.TestingT
	Cleanup(func())
}

// NewCategoryTable creates a new instance of CategoryTable. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewCategoryTable(t mockConstructorTestingTNewCategoryTable) *CategoryTable {
	mock := &CategoryTable{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
