// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	fiber "github.com/gofiber/fiber/v2"
	mock "github.com/stretchr/testify/mock"
)

// CategoryController is an autogenerated mock type for the CategoryController type
type CategoryController struct {
	mock.Mock
}

// Create provides a mock function with given fields: c
func (_m *CategoryController) Create(c *fiber.Ctx) error {
	ret := _m.Called(c)

	var r0 error
	if rf, ok := ret.Get(0).(func(*fiber.Ctx) error); ok {
		r0 = rf(c)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindAll provides a mock function with given fields: c
func (_m *CategoryController) FindAll(c *fiber.Ctx) error {
	ret := _m.Called(c)

	var r0 error
	if rf, ok := ret.Get(0).(func(*fiber.Ctx) error); ok {
		r0 = rf(c)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewCategoryController interface {
	mock.TestingT
	Cleanup(func())
}

// NewCategoryController creates a new instance of CategoryController. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewCategoryController(t mockConstructorTestingTNewCategoryController) *CategoryController {
	mock := &CategoryController{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
