// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	entity "forum-app/entity"

	mock "github.com/stretchr/testify/mock"
)

// CategoryService is an autogenerated mock type for the CategoryService type
type CategoryService struct {
	mock.Mock
}

// FindAll provides a mock function with given fields:
func (_m *CategoryService) FindAll() []entity.Category {
	ret := _m.Called()

	var r0 []entity.Category
	if rf, ok := ret.Get(0).(func() []entity.Category); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Category)
		}
	}

	return r0
}

// Save provides a mock function with given fields: category
func (_m *CategoryService) Save(category entity.Category) entity.Category {
	ret := _m.Called(category)

	var r0 entity.Category
	if rf, ok := ret.Get(0).(func(entity.Category) entity.Category); ok {
		r0 = rf(category)
	} else {
		r0 = ret.Get(0).(entity.Category)
	}

	return r0
}

type mockConstructorTestingTNewCategoryService interface {
	mock.TestingT
	Cleanup(func())
}

// NewCategoryService creates a new instance of CategoryService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewCategoryService(t mockConstructorTestingTNewCategoryService) *CategoryService {
	mock := &CategoryService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
